# see:
# * https://fly.io/docs/blueprints/review-apps-guide
# * https://github.com/superfly/fly-pr-review-apps/blob/1.2.1/README.md

name: Fly Review
on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  FLY_ORG: mmmines
  FLY_REGION: ord

jobs:
  review:
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.deploy.outputs.url }}
    # ensure only one deployment runs at a time
    concurrency:
      group: pr-${{ github.event.number }}
    environment:
      name: review
      url: ${{ steps.deploy.outputs.url }}

    steps:
      - uses: actions/checkout@v4
      - id: deploy
        uses: superfly/fly-pr-review-apps@1.2.1
        with:
          name: pr-${{ github.event.number }}-mmmines
          secrets: |
            BASE_URL=https://pr-${{ github.event.number }}-mmmines.fly.dev
            REDIS_URL=${{ secrets.REDIS_URL }}
